replicaCount: 2

image:
  repository: adarshjain428/bankapp
  blueTag: blue
  greenTag: v6

activeColor: green   # change to green for promotion

service:
  port: 80
  targetPort: 8080

database:
  image: mysql:8
  rootPassword: Test@123
  name: bankappdb

spring:
  profile:
    blue: blue
    green: green

istio:
  gateway:
    name: bankapp-gateway
    hosts:
      - bankapp.adarsh-jain-ecom.infinityfreeapp.com
