apiVersion: apps/v1
kind: Deployment
metadata:
  name: bankapp-green
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: bankapp
      version: green
  template:
    metadata:
      labels:
        app: bankapp
        version: green
    spec:
      containers:
      - name: bankapp
        image: "{{ .Values.image.repository }}:{{ .Values.image.greenTag }}"
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://mysql-service:3306/{{ .Values.database.name }}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
        - name: SPRING_DATASOURCE_USERNAME
          value: root
        - name: SPRING_DATASOURCE_PASSWORD
          value: {{ .Values.database.rootPassword }}
        - name: SPRING_PROFILES_ACTIVE
          value: {{ .Values.spring.profile.green }}
